Feat rn atomic css
didi/mpx pull request #1788
Opened 2024-12-27 09:27 UTC by CommanderXL

2025-03-31 07:52 UTC, hiyuki commented on legacy/windicss-plugin/lib/index.js
> -      delete require.cache[filepath]
为啥改这个？

2025-03-31 08:13 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { unoClassMap = {}, unoVarClassMap = {}, unoPreflightsClassMap = {} } = global.__getUnoClass?.() || {}
这三个classMap分别是啥？

2025-03-31 08:15 UTC, hiyuki commented on packages/unocss-base/lib/index.js
> +    extraPresets.push(presetLegacyCompat({
这个是干嘛的

2025-03-31 08:17 UTC, hiyuki commented on packages/unocss-base/preset-rn/rules/background.js
> +  'bg-repeat-x',
这些应该都不支持

2025-03-31 08:18 UTC, hiyuki commented on packages/unocss-base/lib/index.js
> +    presets: extraPresets
这个和presetUno是个什么合并规则？

2025-03-31 08:20 UTC, hiyuki commented on packages/unocss-base/preset-rn/rules/positions.js
> +const unSupport = ['sticky', 'fixed']
目前支持fixed

2025-03-31 08:22 UTC, hiyuki commented on packages/unocss-base/preset-rn/rules/transition.js
> +export { transitions } from '@unocss/preset-mini/rules'
不支持transition

2025-03-31 08:23 UTC, hiyuki commented on packages/unocss-base/preset-rn/rules/typography.js
> +import {
很多东西应该也不支持

2025-03-31 08:24 UTC, hiyuki commented on packages/unocss-base/preset-rn/variants/index.js
> +  variantAria,
variant应该也有很多不支持

2025-03-31 08:25 UTC, hiyuki commented on packages/unocss-plugin/lib/index.js
> +import platformPreflightsMap from './platform.js'
干掉.js

2025-03-31 08:27 UTC, hiyuki commented on packages/unocss-plugin/lib/index.js
> +import {
先不用改esm保持对旧版本node的兼容性，未来要升级也应该整体升级，不应该只升这一个

2025-03-31 08:59 UTC, hiyuki commented on packages/unocss-plugin/lib/web-plugin/transform-loader.js
> +import * as path from 'path'
需要考虑持久化缓存场景

2025-03-31 10:12 UTC, hiyuki commented on packages/webpack-plugin/lib/react/processStyles.js
> +              const formatValue = global.__formatValue
后面得考虑原子类产物的分包输出

2025-03-31 10:14 UTC, hiyuki commented on packages/webpack-plugin/lib/template-compiler/compiler.js
> +function processVariants (staticClass = '', variants) {
variant要支持的话应该运行时解析吧

2025-05-29 07:44 UTC, CommanderXL commented on packages/unocss-base/lib/index.js
> +    extraPresets.push(presetLegacyCompat({
@hiyuki  unocss 目前生成的 rgb(a) 是用的 space style 的语法形式 rgb(255 255 255)，在之前的 rn 版本上不支持这个语法格式，仅支持 rgb(a) 是 comma style 的语法 rgb(255, 255, 255)，所以用这个 preset 单独将语法统一为 comma style。 （不过目前看 rn 文档是支持了 comma style，后续会再测试确认下，来看下是否还需要这个 preset ）

2025-05-29 08:02 UTC, CommanderXL commented on packages/unocss-base/preset-rn/rules/background.js
> +  'bg-repeat-x',
@hiyuki 这些单独罗列出来的规则都是不支持的。目前主要是利用 unocss blocklist 的规则，所以是将这些不支持的规则单独摘出来了

2025-05-29 08:42 UTC, CommanderXL commented on packages/webpack-plugin/lib/template-compiler/compiler.js
> +function processVariants (staticClass = '', variants) {
@hiyuki 目前的流程是在编译阶段是将各种 variant 统一处理为标准解析格式，然后在运行时 `styleHelperMixin` 里面统一再去处理。

2025-05-29 08:56 UTC, CommanderXL commented on packages/unocss-base/lib/index.js
> +    presets: extraPresets
@hiyuki  merge 的规则。目前是将 presetUno 作为最基础的规则集合，rn 的规则会覆盖 presetUno 的规则。

2025-06-16 07:32 UTC, mater1996 commented on packages/unocss-plugin/lib/index.js
> +import platformPreflightsMap from './platform.js'
commonjs 引入 esModule 不带.js会报找不到模块的错误

2025-06-19 07:52 UTC, mater1996 commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { unoClassMap = {}, unoVarClassMap = {}, unoPreflightsClassMap = {} } = global.__getUnoClass?.() || {}
unocssClassMap就是所有的unocss的样式类，例如
```
'bg-gray-200': {
    '--un-bg-opacity': 1,
    backgroundColor: 'rgba(229, 231, 235, var(--un-bg-opacity))'
  }
```

2025-06-19 07:58 UTC, mater1996 commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { unoClassMap = {}, unoVarClassMap = {}, unoPreflightsClassMap = {} } = global.__getUnoClass?.() || {}
unoPreflightsClassMap是unocss的全局var变量，会作为前置属性被unoClassMap覆盖例如`transform-rotate-y-45`
unocssClassMap为
```
'transform-rotate-y-45': {
    '--un-rotate': '0deg',
    '--un-rotate-y': '45deg',
    transform:
      'translateX(var(--un-translate-x)) translateY(var(--un-translate-y)) rotate(var(--un-rotate)) rotateX(var(--un-rotate-x)) rotateY(var(--un-rotate-y)) rotateZ(var(--un-rotate-z)) skewX(var(--un-skew-x)) skewY(var(--un-skew-y)) scaleX(var(--un-scale-x)) scaleY(var(--un-scale-y))'
  }
```
unoPreflightsClassMap为
```
{
  '--un-rotate': '0deg',
  '--un-rotate-x': '0deg',
  '--un-rotate-y': '0deg',
  '--un-rotate-z': '0deg',
  '--un-scale-x': 1,
  '--un-scale-y': 1,
  '--un-scale-z': 1,
  '--un-skew-x': '0deg',
  '--un-skew-y': '0deg',
  '--un-translate-x': 0,
  '--un-translate-y': 0,
  '--un-translate-z': 0,
}
```

2025-06-19 08:07 UTC, mater1996 commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { unoClassMap = {}, unoVarClassMap = {}, unoPreflightsClassMap = {} } = global.__getUnoClass?.() || {}
unoVarClassMap是工具类，单独提取出一层是为了优先级问题，例如class=‘bg-op-0 bg-red’在web上是
![image](https://github.com/user-attachments/assets/acd5fc7a-e9d1-4bc8-a74e-8313edf7bd9d)
bg-op-0 会覆盖bg-red，但是在rn，bg-red会覆盖bg-op-0,是按照class顺序来的，所以这里将bg-op-0提取出来，单独作为一层后置覆盖

2025-06-25 08:32 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { unoClassMap = {}, unoVarClassMap = {}, unoPreflightsClassMap = {} } = global.__getUnoClass?.() || {}
可以基于一个支持css优先级的泛化方案来实现

2025-06-25 08:39 UTC, hiyuki commented on packages/unocss-base/preset-rn/rules/background.js
> +  'bg-repeat-x',
block这块改清晰一点吧

2025-06-25 08:52 UTC, hiyuki commented on packages/webpack-plugin/lib/react/style-helper.js
> +  formatValueFn = formatValueFn || 'global.__formatValue'
确认一下global是否可以访问，以及当前这个formatValueFn是在哪挂的？

2025-06-25 08:55 UTC, hiyuki commented on packages/webpack-plugin/lib/template-compiler/compiler.js
> +      if (unoStaticHoverClass) {
这里需要判断hover才加

2025-12-09 09:57 UTC, hiyuki commented on packages/unocss-plugin/lib/index.js
> +          checkApplyReg = new RegExp(`(${checkApplyList.join('|')})(\s)?\:`)
为啥不把这个放到cssRequiresTransform中

2025-12-09 11:22 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> -        this.__getSizeCount()
这段逻辑得保留，触发后续屏幕变化刷新样式

2025-12-09 11:40 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +            } else if (unoClassMap[className]) {
unoClassMap整体需要参考local/appclassmap的按需执行设计，并且需要支持rpx，vw等样式刷新

2025-12-09 11:42 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        const { mergeToLayer, genResult } = createLayer(isNativeStaticStyle)
需要进行一个测速，添加了unocss逻辑之后getStyle的耗时增加了多少，

2025-12-09 11:43 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +              mergeToLayer('important', unoVarClassMap[className]._default)
为啥var需要单独拿出来啊

2025-12-09 12:01 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +            } else if (unoClassMap[className]) {
unoClassMap能合到AppClassMap中吗，包括preflightMap

2025-12-09 12:23 UTC, hiyuki commented on packages/unocss-plugin/lib/rn-plugin/index.js
> +        const ctx = await createContext(configOrPath, defaults)
这块初始化的方式可以和Web拉齐一下

2025-12-09 12:32 UTC, hiyuki commented on packages/webpack-plugin/lib/template-compiler/compiler.js
> +  const pseudoClassReg = new RegExp(`(hover)(?:${separators})`) // 目前仅处理了 hover 状态
感觉不需要处理这个，应该让用户在hover-class当中写原子类，不过小程序和web需要支持一下

2025-12-09 12:37 UTC, hiyuki commented on packages/webpack-plugin/lib/react/processStyles.js
> +            output += `
需要变更生成方式，做到布局响应和按需

2026-03-24 08:24 UTC, hiyuki commented on docs-vitepress/guide/platform/platform.md
> +# 跨端输出基础
这个文档的变更是为啥？

2026-03-24 10:23 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +    layerMap,
是不是没有导出的必要

2026-03-24 10:44 UTC, hiyuki commented on packages/webpack-plugin/lib/react/style-helper.js
> +            layerObj._layer = '"important"'
普通的!important也可以支持一下

2026-05-06 12:00 UTC, hiyuki commented on packages/webpack-plugin/lib/react/style-helper.js
> +            classMap[key]._layer = layer
这个important的实现有点割裂

2026-05-06 12:23 UTC, hiyuki commented on packages/webpack-plugin/lib/react/style-helper.js
> +            classMap[key]._layer = layer
统一成_important或者_layers额外属性进行处理吧，并且可以覆盖到内联style

2026-06-10 09:49 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +      isNativeStyle ? layer.push(v) : Object.assign(layer, v)
最终得到的样式对象中会包含_inlineLayer属性么？

2026-06-10 09:52 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +    const v = formatValue(styleObj[prop])
这会有问题吧

2026-06-10 09:53 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +    const v = formatValue(styleObj[prop])
应该先切important再format

2026-06-10 09:55 UTC, hiyuki commented on packages/unocss-base/preset-rn/postprocess/flatten-color-vars.js
> +// `_inlineLayer.important` 里，再由 `transformStyleObj` 通过 `endsWith('!important')`
这是两条链路吧，注释生成的有问题?

2026-06-10 09:58 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +  const mergeToLayer = (name, ...classObjs) => {
改成固定单参数吧，我记得动态解析参数的耗时不低

2026-06-10 09:59 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +      isNativeStyle ? layer.push(v) : Object.assign(layer, v)
有的话进行移除

2026-06-15 08:38 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +    preflight: isNativeStyle ? [] : {},
可以统一存为数组格式，最终合并的时候区分处理就可以

2026-07-03 08:32 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +        Object.assign(
合并完之后移除_inlineLayer吧，上面数组那个分支不用管了

2026-07-14 06:53 UTC, hiyuki requested changes
本轮建议 Request changes。当前存在会导致包无法加载、既有接入方式失效以及 Harmony RN 构建异常的阻断问题，详见 inline comments。

另外，本 PR 新增了 RN 原子类能力与跨端行为差异，但 changed files 中没有同步 `.agents/skills/mpx2rn/`。按仓库 AGENTS.md 的强制约束，需要在同一次改动中更新相关 RN 样式能力参考/最佳实践。

验证：在基于当前 base 应用 PR diff 的隔离副本中，关键文件 `node --check` 通过；实际 ESM import 稳定复现 `ERR_MODULE_NOT_FOUND`。

2026-07-14 06:53 UTC, hiyuki commented on packages/unocss-base/lib/index.js
> +import presetRn from '../preset-rn/index'
[P1] 该包已经声明为 ESM，但这里以及 `preset-rn/` 下的相对 import 都缺少 `.js` 扩展名。Node ESM 不会自动补扩展名；隔离副本执行 import 时稳定报 `ERR_MODULE_NOT_FOUND: .../preset-rn/rules/index`，导致 `@mpxjs/unocss-base` 在读取配置前就无法加载。请为所有相对 ESM specifier 补齐 `.js`，或通过构建产物/exports 统一处理。

2026-07-14 06:53 UTC, hiyuki commented on packages/unocss-base/lib/index.js
> +  const isReact = mpxCurrentTargetMode === 'ios' || mpxCurrentTargetMode === 'android'
[P1] `@mpxjs/webpack-plugin/lib/utils/env` 已将 `harmony` 归为 React 模式，但这里仅包含 iOS/Android，导致 Harmony 会运行 RN UnoCSS 插件却没有加载 RN preset、blocklist 和 preflight。transform/filter 类还会让运行时请求一个 `undefined` preflight，随后 `mergeToLayer` 访问 `style._inlineLayer` 时可能直接抛错。这里需要包含 `harmony`，并建议复用统一的 `isReact` 判断。

2026-07-14 06:53 UTC, hiyuki commented on packages/unocss-base/package.json
> +  "type": "module",
[P1] 改为 `type: module` 并改用 default export 后，现有公开文档中的 `const presetMpx = require('@mpxjs/unocss-base')` 会失效：旧 Node 报 `ERR_REQUIRE_ESM`，支持同步 require(ESM) 的新版 Node 也返回 namespace object，无法直接调用。同样的问题也存在于 `@mpxjs/unocss-plugin` 的 `new MpxUnocssPlugin()` 接入。需要提供 `exports.require`/CJS wrapper，或完整迁移所有调用方、文档和 Node 支持基线。

2026-07-14 06:53 UTC, hiyuki commented on packages/unocss-base/package.json
> +    "@unocss/preset-legacy-compat": "^66.0.0"
[P1] 新增的 `preset-rn` 多处直接 import `@unocss/preset-mini/rules`、`variants` 和 `utils`，但本包没有声明 `@unocss/preset-mini` 直接依赖。依赖严格隔离的 pnpm 安装下不能依赖 `preset-wind3` 的传递依赖，会直接找不到模块；请将实际直接 import 的包加入 dependencies。

2026-07-14 06:53 UTC, hiyuki commented on packages/unocss-plugin/lib/index.js
> +  if (transformCSS) transformCSS = transformCSS instanceof Object ? transformGroups : {}
[P2] 对象形式的 `transformCSS` 在这里被错误赋值成了 `transformGroups`。例如传入 `{ applyVariable: ['--at-apply'] }` 且未配置 transformGroups 时，transformCSS 会变成 `undefined`，后续 directive transformer 和 `cssRequiresTransform` 都不会生效。这里应保留/规范化 `transformCSS` 自身。

2026-07-14 06:53 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +          mergeToLayer('important', { ...HIDE_STYLE })
[P2] 这是 RN 运行时代码，使用对象 spread 合并违反仓库 AGENTS.md 的强制编码约束。请改为 `Object.assign({}, HIDE_STYLE)`（如果后续不会修改对象，也可以评估直接复用常量）。

2026-07-14 08:24 UTC, hiyuki commented on packages/core/src/platform/builtInMixins/styleHelperMixin.ios.js
> +          mergeToLayer('important', Object.assign({}, HIDE_STYLE))
直接merge HIDE_STYLE就可以了吧，mergeToLayer不会修改原对象吧

2026-07-14 09:30 UTC, hiyuki approved these changes

2026-07-14 09:30 UTC, merged